// <auto-generated />
using System;
using BudgetTracker.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BudgetTracker.Infrastructure.Migrations
{
    [DbContext(typeof(SqliteContext))]
    [Migration("20250804144303_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("BudgetTracker.Infrastructure.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Food and supermarket purchases",
                            Name = "Groceries"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Electricity, water, gas, etc.",
                            Name = "Utilities"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Public transport, fuel, etc.",
                            Name = "Transport"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Entertainment and hobbies",
                            Name = "Leisure"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Miscellaneous expenses",
                            Name = "Other"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Trips, vacations, hotels, flights",
                            Name = "Travel"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Medical, pharmacy, insurance",
                            Name = "Health"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Professional and personal services",
                            Name = "Services"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Insurance premiums and payments",
                            Name = "Insurance"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Crypto, shares, investments",
                            Name = "Assets"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Loan payments and repayments",
                            Name = "Loan"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Charity and donations",
                            Name = "Donation"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Income from employment",
                            Name = "Salary"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Received or given gifts",
                            Name = "Gifts"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Interest income or expenses",
                            Name = "Interest"
                        });
                });

            modelBuilder.Entity("BudgetTracker.Infrastructure.Models.RecurringTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Pattern")
                        .HasMaxLength(20)
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasMaxLength(20)
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("RecurringTransactions");
                });

            modelBuilder.Entity("BudgetTracker.Infrastructure.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RecurringTransactionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasMaxLength(20)
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("RecurringTransactionId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("BudgetTracker.Infrastructure.Models.RecurringTransaction", b =>
                {
                    b.HasOne("BudgetTracker.Infrastructure.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BudgetTracker.Infrastructure.Models.Transaction", b =>
                {
                    b.HasOne("BudgetTracker.Infrastructure.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BudgetTracker.Infrastructure.Models.RecurringTransaction", "RecurringTransaction")
                        .WithMany("GeneratedTransactions")
                        .HasForeignKey("RecurringTransactionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("RecurringTransaction");
                });

            modelBuilder.Entity("BudgetTracker.Infrastructure.Models.RecurringTransaction", b =>
                {
                    b.Navigation("GeneratedTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
