// <auto-generated />
using System;
using BudgetTracker.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BudgetTracker.Infrastructure.Migrations
{
    [DbContext(typeof(SqliteContext))]
    partial class SqliteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("BudgetTracker.Infrastructure.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Food, drinks, and supermarket purchases",
                            Name = "Groceries"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Restaurants, cafes, takeaways, bars",
                            Name = "Dining Out"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Electricity, water, gas, internet, phone",
                            Name = "Utilities"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Rent, mortgage, property maintenance",
                            Name = "Housing"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Public transport, fuel, tolls",
                            Name = "Transport"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Car payments, repairs, insurance",
                            Name = "Vehicle"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Movies, hobbies, games, streaming services",
                            Name = "Entertainment"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Trips, vacations, hotels, flights",
                            Name = "Travel"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Medical, dental, pharmacy, health insurance",
                            Name = "Health"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Haircuts, beauty, grooming",
                            Name = "Personal Care"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Courses, books, learning materials",
                            Name = "Education"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Professional, repair, or cleaning services",
                            Name = "Services"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Premiums for health, life, property",
                            Name = "Insurance"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Crypto, shares, bonds, assets",
                            Name = "Investments"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Loan payments and repayments",
                            Name = "Loan"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Charity and contributions",
                            Name = "Donations"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Income from employment",
                            Name = "Salary"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Freelance or business earnings",
                            Name = "Business Income"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Received or given gifts",
                            Name = "Gifts"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Interest income or loan interest paid",
                            Name = "Interest"
                        },
                        new
                        {
                            Id = 21,
                            Description = "Income tax, property tax, other taxes",
                            Name = "Taxes"
                        },
                        new
                        {
                            Id = 22,
                            Description = "Transfers to savings or emergency funds",
                            Name = "Savings"
                        },
                        new
                        {
                            Id = 23,
                            Description = "Miscellaneous expenses",
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("BudgetTracker.Infrastructure.Models.RecurringTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Pattern")
                        .HasMaxLength(20)
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasMaxLength(20)
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("RecurringTransactions");
                });

            modelBuilder.Entity("BudgetTracker.Infrastructure.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RecurringTransactionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasMaxLength(20)
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("RecurringTransactionId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("BudgetTracker.Infrastructure.Models.RecurringTransaction", b =>
                {
                    b.HasOne("BudgetTracker.Infrastructure.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BudgetTracker.Infrastructure.Models.Transaction", b =>
                {
                    b.HasOne("BudgetTracker.Infrastructure.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BudgetTracker.Infrastructure.Models.RecurringTransaction", "RecurringTransaction")
                        .WithMany("GeneratedTransactions")
                        .HasForeignKey("RecurringTransactionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("RecurringTransaction");
                });

            modelBuilder.Entity("BudgetTracker.Infrastructure.Models.RecurringTransaction", b =>
                {
                    b.Navigation("GeneratedTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
